# Generated by Django 4.1.3 on 2022-11-07 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cat',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('self care', 'Self Care'), ('salary', 'Salary'), ('health_and_fitness', 'Health And Fitness'), ('cafe', 'Cafe'), ('education', 'Education'), ('car', 'Car'), ('relaxation', 'Relaxation'), ('Payments, commissions', 'Payments'), ('Shopping: clothes, appliances', 'Shopping'), ('products', 'Products'), ('travel', 'Travel')], max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
