# Generated by Django 4.1.3 on 2022-11-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_cat_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cat', models.CharField(choices=[('self care', 'Self Care'), ('salary', 'Salary'), ('health_and_fitness', 'Health And Fitness'), ('cafe', 'Cafe'), ('education', 'Education'), ('car', 'Car'), ('relaxation', 'Relaxation'), ('Payments, commissions', 'Payments'), ('Shopping: clothes, appliances', 'Shopping'), ('products', 'Products'), ('travel', 'Travel')], max_length=120)),
                ('organisation', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
